baseurl = "https://kupczynski.info"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "Igor Kupczyński"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/post/:slug/"

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 1
[[menu.main]]
name = "Legal"
url = "/legal/"
weight = 2
[[menu.main]]
name = "About"
url = "https://github.com/igor-kupczynski"
wieght = 3
[[menu.feed]]
name = "Subscribe"
url = "/index.xml"

[params]
custom_css = ["css/theme-override.css"]
description = "Description TBD."
footer = "© 2022 Igor Kupczyński. [Views are my own](/legal/)."

[frontmatter]
date = [':filename', ':default']
